name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get : ^4.7.3
  
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8 
  
  # --- DİL VE TARİH ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- VERİ TABANI (LOCAL) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # --- PROJE ARAÇLARI ---
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.1
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  
  # --- DİĞER YARDIMCILAR ---
  path_provider: ^2.1.2
  flutter_local_notifications: ^21.0.0-dev.2
  timezone: ^0.11.0
  firebase_messaging: ^14.9.4
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true 